#!/bin/bash

# -------- Set up the environment to source common tools & conf ------------
if [ -z "${ONE_LOCATION}" ]; then
    LIB_LOCATION=/usr/lib/one
else
    LIB_LOCATION=$ONE_LOCATION/lib
fi

. $LIB_LOCATION/sh/scripts_common.sh

HOOK_PATH=$(dirname $0)

# -------- Call DNS update script ------------
ID=$1
TEMPLATE=$2

`$HOOK_PATH/pdns-update-host UPDATE "${ID}" "${TEMPLATE}"`
