#!/bin/bash

# -------------------------------------------------------------------------- #
# Copyright 2014, Asociacion Clubs Baloncesto (acb.com)                      #
# Author: Joaquin Villanueva                                                 #
#                                                                            #
# Portions copyright OpenNebula Project (OpenNebula.org), CG12 Labs          #
#                                                                            #
# Licensed under the Apache License, Version 2.0 (the "License"); you may    #
# not use this file except in compliance with the License. You may obtain    #
# a copy of the License at                                                   #
#                                                                            #
# http://www.apache.org/licenses/LICENSE-2.0                                 #
#                                                                            #
# Unless required by applicable law or agreed to in writing, software        #
# distributed under the License is distributed on an "AS IS" BASIS,          #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
# See the License for the specific language governing permissions and        #
# limitations under the License.                                             #
#--------------------------------------------------------------------------- #

# clone fe:SOURCE host:remote_system_ds/disk.i vm_id ds_id
#   - fe is the front-end hostname
#   - SOURCE is the path of the disk image in the form DS_BASE_PATH/disk
#   - host is the target host to deploy the VM
#   - remote_system_ds is the path for the system datastore in the host
#   - vmid is the id of the VM
#   - dsid is the target datastore (0 is the system datastore)

SRC=$1
DST=$2

VMID=$3
DSID=$4

if [ -z "${ONE_LOCATION}" ]; then
    TMCOMMON=/var/lib/one/remotes/tm/tm_common.sh
else
    TMCOMMON=$ONE_LOCATION/var/remotes/tm/tm_common.sh
fi

 . $TMCOMMON

EQL_MAD_DEBUG=1
TM_PATH=$(dirname $0)
source ${TM_PATH}/../../datastore/eqliscsi/eqliscsi.conf
source ${TM_PATH}/../../scripts_eqliscsi.sh


#-------------------------------------------------------------------------------
# Get EQL vars from datastore/image
#-------------------------------------------------------------------------------
# Get disk id from DST path
DST_PATH=`arg_path $DST`
DISK_ID=$(echo "$DST_PATH" | $AWK -F. '{print $NF}')

XPATH="${TM_PATH}/../../datastore/xpath.rb --stdin"

unset i XPATH_ELEMENTS
while IFS= read -r -d '' element; do
    XPATH_ELEMENTS[i++]="$element"
done < <(onevm show -x $VMID| $XPATH \
                    /VM/TEMPLATE/DISK[DISK_ID=$DISK_ID]/DATASTORE_ID \
                    /VM/TEMPLATE/DISK[DISK_ID=$DISK_ID]/IMAGE_ID)

SRC_DSID="${XPATH_ELEMENTS[0]}"
SRC_IMID="${XPATH_ELEMENTS[1]}"

# Get EQL vars from datastore SRC_DSID
unset i XPATH_ELEMENTS
while IFS= read -r -d '' element; do
    XPATH_ELEMENTS[i++]="$element"
done < <(onedatastore show -x $SRC_DSID| $XPATH \
                    /DATASTORE/TEMPLATE/EQL_HOST \
                    /DATASTORE/TEMPLATE/EQL_POOL \
                    /DATASTORE/TEMPLATE/EQL_USER \
                    /DATASTORE/TEMPLATE/EQL_PASS \
                    /DATASTORE/TEMPLATE/EQL_MULTIHOST \
                    /DATASTORE/TEMPLATE/EQL_SECURITY_ACCESS)

# Get EQL vars from image SRC_IMID
while IFS= read -r -d '' element; do
    XPATH_ELEMENTS[i++]="$element"
done < <(oneimage show -x $SRC_IMID| $XPATH \
                    /IMAGE/TEMPLATE/EQL_MULTIHOST \
                    /IMAGE/TEMPLATE/EQL_SECURITY_ACCESS)

EQL_HOST="${XPATH_ELEMENTS[0]:-$EQL_HOST}"
EQL_POOL="${XPATH_ELEMENTS[1]:-$EQL_POOL}"
EQL_USER="${XPATH_ELEMENTS[2]:-$EQL_USER}"
EQL_PASS="${XPATH_ELEMENTS[3]:-$EQL_PASS}"
EQL_MULTIHOST="${XPATH_ELEMENTS[4]:-$EQL_MULTIHOST}"
EQL_SECURITY_ACCESS="${XPATH_ELEMENTS[5]:-"$EQL_SECURITY_ACCESS"}"
# Overwrite datastore defaults with image values for EQL
EQL_MULTIHOST="${XPATH_ELEMENTS[6]:-$EQL_MULTIHOST}"
EQL_SECURITY_ACCESS="${XPATH_ELEMENTS[7]:-"$EQL_SECURITY_ACCESS"}"

#-------------------------------------------------------------------------------
# Set src volume device dst path and dir
#-------------------------------------------------------------------------------

SRC_VOLUME=$(eql_src_get_volume $SRC)

DST_PATH=`arg_path $DST`
DST_HOST=`arg_host $DST`
DST_DIR=`dirname $DST_PATH`

DST_VOLUME="${SRC_VOLUME}-${VMID}"
DST_DEV="$EQL_BASE_DEVICE/$DST_VOLUME"

#-------------------------------------------------------------------------------
# Clone volume and set config
#-------------------------------------------------------------------------------

# Remote volume cloning on Equallogic (returns IQN)
eql_log "Cloning volume $SRC_VOLUME on $EQL_HOST to $DST_VOLUME"
DST_IQN=$(eqladm_target_clone $SRC_VOLUME $DST_VOLUME "Clone $VMID of $SRC_VOLUME")
RC=$?
if [ "$RC" -ne 0 ]; then
    eql_error_message "Error cloning from volume $SRC_VOLUME to $DST_VOLUME on $EQL_HOST"
    exit 1
fi
eql_log "Cloned image $SRC_VOLUME to $DST_VOLUME"

#-------------------------------------------------------------------------------
# Discover target, login and link volume to device
#-------------------------------------------------------------------------------

# Construct command to discover target, login and link the device
DISCOVER_CMD=$(cat <<EOF
    set -e
    mkdir -p $DST_DIR
    $SUDO $(eqliscsi_discovery)
    $SUDO $(eqliscsi_login "$DST_IQN")
    RC=\$?
    if [ "\$RC" -ne 0 ]; then
	exit \$RC
    fi
    # poll 10 secs for iSCSI device
    x=0
    while [ "\$x" -lt 10 -a ! -L "$DST_DEV" ]; do
        x=\$((x+1))
        sleep 1
    done
    if [ -L "$DST_DEV" ]; then
        ln -sf "$DST_DEV" "$DST_PATH"
    else
        echo "iSCSI device "$DST_DEV" not found on time"
        exit 1
    fi
EOF
)

ssh_exec_and_log "$DST_HOST" "$DISCOVER_CMD" "Error logging in $DST_IQN at $DST_HOST or linking $DST_DEV to $DST_PATH"
eql_log "Logged in $DST_VOLUME at $DST_HOST"

exit 0
