#!/bin/sh

# -------------------------------------------------------------------------- #
# Copyright 2014, Asociacion Clubs Baloncesto (acb.com)                      #
# Author: Joaquin Villanueva                                                 #
#                                                                            #
# Portions copyright OpenNebula Project (OpenNebula.org), CG12 Labs          #
#                                                                            #
# Licensed under the Apache License, Version 2.0 (the "License"); you may    #
# not use this file except in compliance with the License. You may obtain    #
# a copy of the License at                                                   #
#                                                                            #
# http://www.apache.org/licenses/LICENSE-2.0                                 #
#                                                                            #
# Unless required by applicable law or agreed to in writing, software        #
# distributed under the License is distributed on an "AS IS" BASIS,          #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
# See the License for the specific language governing permissions and        #
# limitations under the License.                                             #
#--------------------------------------------------------------------------- #
# POSTMIGRATE SOURCE DST template vmid dsid remote_system_dir disk_id src_dsid persistent
#  - SOURCE is the host where the VM is running
#  - DST is the host where the VM is to be migrated
#  - template is the template of the VM in XML and base64 encoded
#  - vmid is the id of the VM
#  - dsid is the target datastore
#  - remote_system_dir is the path for the VM home in the system datastore
#  - disk_id is the DISK ID from the VM
#  - src_dsid is the DATASTORE ID of the VM disk
#  - persistent YES if disk image is persistent. Empty otherwise

# To access the vm_template you can use the xpath.rb utility. Check the
# datastore drivers for an example.

# -------- Set up the environment to source common tools & conf ------------

if [ -z "${ONE_LOCATION}" ]; then
    TMCOMMON=/var/lib/one/remotes/tm/tm_common.sh
else
    TMCOMMON=$ONE_LOCATION/var/remotes/tm/tm_common.sh
fi

. $TMCOMMON

EQL_MAD_DEBUG=1
TM_PATH=$(dirname $0)
source ${TM_PATH}/../../datastore/eqliscsi/eqliscsi.conf
source ${TM_PATH}/../../scripts_eqliscsi.sh

# -------- Get cp and datastore arguments from OpenNebula core ------------

SRC_HOST=$1
DST_HOST=$2
TEMPLATE=$3

VMID=$4
DSID=$5

VM_PATH=$6
DISK_ID=$7
SRC_DSID=$8
PERSISTENT=$9

#-------------------------------------------------------------------------------
# Get EQL_HOST from datastore SRC_DSID
#-------------------------------------------------------------------------------
XPATH="${TM_PATH}/../../datastore/xpath.rb --stdin"

unset i XPATH_ELEMENTS
while IFS= read -r -d '' element; do
    XPATH_ELEMENTS[i++]="$element"
done < <(onedatastore show -x $SRC_DSID| $XPATH \
                    /DATASTORE/TEMPLATE/EQL_HOST)

EQL_HOST="${XPATH_ELEMENTS[0]:-$EQL_HOST}"

#-------------------------------------------------------------------------------
# Retrieve volume name and device
#-------------------------------------------------------------------------------
EQL_VOLUME="$(eql_src_get_volume $VM_PATH)"
# If not persistent, complete volume name
if [ -z "$PERSISTENT" ]; then
    EQL_VOLUME=$EQL_VOLUME-$VMID
fi
EQL_DEV="$EQL_BASE_DEVICE/$EQL_VOLUME"

# Construct command to discover target and login
eql_log "Logging out $EQL_VOLUME at $SRC_HOST"

LOGOUT_CMD=$(cat <<EOF
    set -e
    IQN=\$($SUDO $(eqliscsi_get_iqn_from_node "$EQL_VOLUME"))
    $SUDO $(eqliscsi_logout "\$IQN")
    RC=\$?
    if [ "\$RC" -ne 0 ]; then
        exit \$RC
    fi
EOF
)

eql_log "$SRC_HOST" "$LOGOUT_CMD"
ssh_exec_and_log "$SRC_HOST" "$LOGOUT_CMD" "Log out error at $SRC_HOST:$IQN"
exit 0
