#!/bin/bash

# -------------------------------------------------------------------------- #
# Copyright 2014, Asociacion Clubs Baloncesto (acb.com)                      #
# Author: Joaquin Villanueva                                                 #
#                                                                            #
# Portions copyright OpenNebula Project (OpenNebula.org), CG12 Labs          #
#                                                                            #
# Licensed under the Apache License, Version 2.0 (the "License"); you may    #
# not use this file except in compliance with the License. You may obtain    #
# a copy of the License at                                                   #
#                                                                            #
# http://www.apache.org/licenses/LICENSE-2.0                                 #
#                                                                            #
# Unless required by applicable law or agreed to in writing, software        #
# distributed under the License is distributed on an "AS IS" BASIS,          #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
# See the License for the specific language governing permissions and        #
# limitations under the License.                                             #
#--------------------------------------------------------------------------- #

###############################################################################
# This script is used to clone a VM image (SRC) to the image repository as DST
###############################################################################

# -------- Set up the environment to source common tools & conf ------------

if [ -z "${ONE_LOCATION}" ]; then
    LIB_LOCATION=/usr/lib/one
else
    LIB_LOCATION=$ONE_LOCATION/lib
fi

. $LIB_LOCATION/sh/scripts_common.sh

DRIVER_PATH=$(dirname $0)
source ${DRIVER_PATH}/../libfs.sh
source ${DRIVER_PATH}/eqliscsi.conf
source ${DRIVER_PATH}/../../scripts_eqliscsi.sh

# -------- Get cp and datastore arguments from OpenNebula core ------------

DRV_ACTION=$1
ID=$2

UTILS_PATH="${DRIVER_PATH}/.."

XPATH="$UTILS_PATH/xpath.rb -b $DRV_ACTION"

unset i XPATH_ELEMENTS

while IFS= read -r -d '' element; do
    XPATH_ELEMENTS[i++]="$element"
done < <($XPATH     /DS_DRIVER_ACTION_DATA/DATASTORE/BASE_PATH \
                    /DS_DRIVER_ACTION_DATA/DATASTORE/TEMPLATE/RESTRICTED_DIRS \
                    /DS_DRIVER_ACTION_DATA/DATASTORE/TEMPLATE/SAFE_DIRS \
                    /DS_DRIVER_ACTION_DATA/DATASTORE/TEMPLATE/UMASK \
                    /DS_DRIVER_ACTION_DATA/DATASTORE/TEMPLATE/EQL_HOST \
                    /DS_DRIVER_ACTION_DATA/DATASTORE/TEMPLATE/EQL_POOL \
                    /DS_DRIVER_ACTION_DATA/DATASTORE/TEMPLATE/EQL_USER \
                    /DS_DRIVER_ACTION_DATA/DATASTORE/TEMPLATE/EQL_PASS \
                    /DS_DRIVER_ACTION_DATA/DATASTORE/TEMPLATE/EQL_MULTIHOST \
                    /DS_DRIVER_ACTION_DATA/DATASTORE/TEMPLATE/EQL_SECURITY_ACCESS \
                    /DS_DRIVER_ACTION_DATA/IMAGE/NAME \
                    /DS_DRIVER_ACTION_DATA/IMAGE/PATH \
                    /DS_DRIVER_ACTION_DATA/IMAGE/SIZE \
                    /DS_DRIVER_ACTION_DATA/IMAGE/TEMPLATE/DESCRIPTION \
                    /DS_DRIVER_ACTION_DATA/IMAGE/TEMPLATE/EQL_MULTIHOST \
                    /DS_DRIVER_ACTION_DATA/IMAGE/TEMPLATE/EQL_SECURITY_ACCESS)

BASE_PATH="${XPATH_ELEMENTS[0]}"
RESTRICTED_DIRS="${XPATH_ELEMENTS[1]}"
SAFE_DIRS="${XPATH_ELEMENTS[2]}"
UMASK="${XPATH_ELEMENTS[3]}"
EQL_HOST="${XPATH_ELEMENTS[4]:-$EQL_HOST}"
EQL_POOL="${XPATH_ELEMENTS[5]:-$EQL_POOL}"
EQL_USER="${XPATH_ELEMENTS[6]:-$EQL_USER}"
EQL_PASS="${XPATH_ELEMENTS[7]:-$EQL_PASS}"
EQL_MULTIHOST="${XPATH_ELEMENTS[8]:-$EQL_MULTIHOST}"
EQL_SECURITY_ACCESS="${XPATH_ELEMENTS[9]:-"$EQL_SECURITY_ACCESS"}"
EQL_NEW_VOLUME="$(eql_clean_volume_name "${XPATH_ELEMENTS[10]}")"
EQL_VOLUME="$(eql_src_get_volume ${XPATH_ELEMENTS[11]})"
SIZE="${XPATH_ELEMENTS[12]}"
EQL_VOL_DESCRIPTION="${XPATH_ELEMENTS[13]}"
# Overwrite datastore defaults with image values for EQL
EQL_MULTIHOST="${XPATH_ELEMENTS[14]:-$EQL_MULTIHOST}"
EQL_SECURITY_ACCESS="${XPATH_ELEMENTS[15]:-"$EQL_SECURITY_ACCESS"}"

set_up_datastore "$BASE_PATH" "$RESTRICTED_DIRS" "$SAFE_DIRS" "$UMASK"

# Remote volume cloning on Equallogic (returns IQN)
log "Cloning volume $EQL_VOLUME on $EQL_HOST to $EQL_NEW_VOLUME"
IQN=$(eqladm_target_clone $EQL_VOLUME $EQL_NEW_VOLUME "$EQL_VOL_DESCRIPTION")
ERROR=$?
if [ "$ERROR" -ne 0 ]; then
    log_error "Error cloning from volume $EQL_VOLUME to $EQL_NEW_VOLUME on $EQL_HOST $IQN"
    exit 1
fi
log "Cloned image $IQN to $EQL_NEW_VOLUME"

# Return HOST+IQN
DST="$EQL_HOST:$IQN"

echo "$DST"
