#!/bin/bash

# -------------------------------------------------------------------------- #
# Copyright 2014, Asociacion Clubs Baloncesto (acb.com)                      #
# Author: Joaquin Villanueva                                                 #
#                                                                            #
# Portions copyright OpenNebula Project (OpenNebula.org), CG12 Labs          #
#                                                                            #
# Licensed under the Apache License, Version 2.0 (the "License"); you may    #
# not use this file except in compliance with the License. You may obtain    #
# a copy of the License at                                                   #
#                                                                            #
# http://www.apache.org/licenses/LICENSE-2.0                                 #
#                                                                            #
# Unless required by applicable law or agreed to in writing, software        #
# distributed under the License is distributed on an "AS IS" BASIS,          #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
# See the License for the specific language governing permissions and        #
# limitations under the License.                                             #
#--------------------------------------------------------------------------- #

###############################################################################
# This script is used to create a VM image (EQL_VOLUME) of size (SIZE) and formatted
# as (FS) on Equallogic
###############################################################################

# -------- Set up the environment to source common tools & conf ------------

if [ -z "${ONE_LOCATION}" ]; then
    LIB_LOCATION=/usr/lib/one
else
    LIB_LOCATION=$ONE_LOCATION/lib
fi

. $LIB_LOCATION/sh/scripts_common.sh

EQL_MAD_DEBUG=1
DRIVER_PATH=$(dirname $0)
source ${DRIVER_PATH}/../libfs.sh
source ${DRIVER_PATH}/eqliscsi.conf
source ${DRIVER_PATH}/../../scripts_eqliscsi.sh

# -------- Get mkfs and datastore arguments from OpenNebula core ------------

DRV_ACTION=$1
IMID=$2

UTILS_PATH="${DRIVER_PATH}/.."
XPATH="$UTILS_PATH/xpath.rb -b $DRV_ACTION"

unset i XPATH_ELEMENTS
while IFS= read -r -d '' element; do
    XPATH_ELEMENTS[i++]="$element"
done < <($XPATH     /DS_DRIVER_ACTION_DATA/DATASTORE/BASE_PATH \
                    /DS_DRIVER_ACTION_DATA/DATASTORE/TEMPLATE/RESTRICTED_DIRS \
                    /DS_DRIVER_ACTION_DATA/DATASTORE/TEMPLATE/SAFE_DIRS \
                    /DS_DRIVER_ACTION_DATA/DATASTORE/TEMPLATE/UMASK \
                    /DS_DRIVER_ACTION_DATA/DATASTORE/TEMPLATE/EQL_HOST \
                    /DS_DRIVER_ACTION_DATA/DATASTORE/TEMPLATE/EQL_POOL \
                    /DS_DRIVER_ACTION_DATA/DATASTORE/TEMPLATE/EQL_USER \
                    /DS_DRIVER_ACTION_DATA/DATASTORE/TEMPLATE/EQL_PASS \
                    /DS_DRIVER_ACTION_DATA/DATASTORE/TEMPLATE/EQL_MULTIHOST \
                    /DS_DRIVER_ACTION_DATA/DATASTORE/TEMPLATE/EQL_SECURITY_ACCESS \
                    /DS_DRIVER_ACTION_DATA/DATASTORE/TEMPLATE/EQL_THINPROVISION \
                    /DS_DRIVER_ACTION_DATA/IMAGE/NAME \
                    /DS_DRIVER_ACTION_DATA/IMAGE/TEMPLATE/DESCRIPTION \
                    /DS_DRIVER_ACTION_DATA/IMAGE/FSTYPE \
                    /DS_DRIVER_ACTION_DATA/IMAGE/SIZE \
                    /DS_DRIVER_ACTION_DATA/IMAGE/TEMPLATE/EQL_MULTIHOST \
                    /DS_DRIVER_ACTION_DATA/IMAGE/TEMPLATE/EQL_SECURITY_ACCESS \
                    /DS_DRIVER_ACTION_DATA/IMAGE/TEMPLATE/EQL_THINPROVISION)

BASE_PATH="${XPATH_ELEMENTS[0]}"
RESTRICTED_DIRS="${XPATH_ELEMENTS[1]}"
SAFE_DIRS="${XPATH_ELEMENTS[2]}"
UMASK="${XPATH_ELEMENTS[3]}"
EQL_HOST="${XPATH_ELEMENTS[4]:-$EQL_HOST}"
EQL_POOL="${XPATH_ELEMENTS[5]:-$EQL_POOL}"
EQL_USER="${XPATH_ELEMENTS[6]:-$EQL_USER}"
EQL_PASS="${XPATH_ELEMENTS[7]:-$EQL_PASS}"
EQL_MULTIHOST="${XPATH_ELEMENTS[8]:-$EQL_MULTIHOST}"
EQL_SECURITY_ACCESS="${XPATH_ELEMENTS[9]:-"$EQL_SECURITY_ACCESS"}"
EQL_THINPROVISION="${XPATH_ELEMENTS[10]:-"$EQL_THINPROVISION"}"
EQL_VOLUME="$(eql_clean_volume_name "${XPATH_ELEMENTS[11]}").${IMID}"
EQL_VOL_DESCRIPTION="${XPATH_ELEMENTS[12]}"
FSTYPE="${XPATH_ELEMENTS[13]}"
SIZE="${XPATH_ELEMENTS[14]:-0}"
# Overwrite datastore defaults with image values for EQL
EQL_MULTIHOST="${XPATH_ELEMENTS[15]:-$EQL_MULTIHOST}"
EQL_SECURITY_ACCESS="${XPATH_ELEMENTS[16]:-"$EQL_SECURITY_ACCESS"}"
EQL_THINPROVISION="${XPATH_ELEMENTS[17]:-"$EQL_THINPROVISION"}"

set_up_datastore "$BASE_PATH" "$RESTRICTED_DIRS" "$SAFE_DIRS" "$UMASK"

DEV="$EQL_BASE_DEVICE/$EQL_VOLUME"

# ------------ Create the image to the repository ------------

# If image type is save_as, exit. We don't need to create in advance the volume
if [ "$FSTYPE" = "save_as" ]; then
    echo "$EQL_VOLUME"
    exit 0
fi

# Remote volume create on Equallogic (returns IQN)
eql_log "Creating volume $EQL_VOLUME on $EQL_HOST"
IQN=$(eqladm_target_new $EQL_POOL $EQL_VOLUME $SIZE "$EQL_VOL_DESCRIPTION")
RC=$?
if [ "$RC" -ne 0 ]; then
    error_message "Error creating volume $EQL_VOLUME on $EQL_HOST $IQN"
    exit 1
fi

# If FSTYPE not raw, create filesystem
if [ "$FSTYPE" != "raw" ]; then
    # Discover iscsi target
    eql_log "Discover targets from $EQL_HOST"
    exec_and_log "$SUDO $(eqliscsi_discovery)" "Error discovering targets from $EQL_HOST"

    # Connect to iscsi target and login
    eql_log "Connecting to $EQL_HOST:$IQN"
    exec_and_log "$SUDO $(eqliscsi_login $IQN)" "Error connecting to $EQL_HOST:$IQN"

    # Wait connection
    sleep $EQL_WAIT_TIME

    # Create partition on device
    ERROR=""
    eql_log "Creating partition on $DEV"
    exec_and_set_error "$SUDO parted -s $DEV mktable gpt" "Error creating partition label on $DEV"

    if [ -z "$ERROR" ]; then
	exec_and_set_error "$SUDO parted -s $DEV mkpart primary 0% 100%" "Error creating partition on $DEV"
        if [ -z "$ERROR" ]; then
	    # Create filesystem on device
	    eql_log "Creating filesystem $FSTYPE on $DEV"
	    PARTITION="${DEV}p1"
	    # Wait partition appearance after udev processing
	    sleep $EQL_WAIT_TIME
	    exec_and_set_error "$SUDO $(mkfs_command "$PARTITION" "$FSTYPE")" "Error creating filesystem $FSTYPE on $PARTITION"
	fi
    fi

    # Let continue to disconnect target ever if ended in error
    # Disconnect target
    eql_log "Disconnecting from $EQL_HOST:$IQN"
    exec_and_log "$SUDO $(eqliscsi_logout $IQN)" "Error disconnecting from $EQL_HOST:$IQN"

    # Exits if create filesystem or disconnect ends with error
    if [ ! -z "$ERROR" ]; then
	exit 1
    fi
fi

# Return VOLUME NAME
echo "$EQL_VOLUME"
